@host=http://127.0.0.1:9899

### new accounts
POST {{host}}/accounts
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
  "currency": "USD"
}

### get account
GET {{host}}/accounts/2
Authorization: Bearer {{login.response.body.access_token}}


### get account list
GET {{host}}/accounts?page_id=1&page_size=5
Authorization: Bearer {{login.response.body.access_token}}


### create transfer
POST {{host}}/transfers
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
  "from_account_id": 1,
  "to_account_id": 2,
  "amount": 100,
  "currency": "USD"
}

### create user
POST {{host}}/users
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
  "username": "wuyue3",
  "password": "123456",
  "email": "1020@11.com",
  "full_name": "USD"
}


### login user
# @name login
POST {{host}}/users/login  
Content-Type: application/json

{
  "username": "wuyue3",
  "password": "123456"
}
