version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    networks:
      - bank-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      - bank-network
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
    ]
    command: [ "/app/main" ]

networks:
  bank-network:
    driver: bridge
